---
editUrl: false
next: false
prev: false
title: "LixServerError"
---

Defined in: lix-cache-sdk/src/errors.ts:91

Error thrown when the server returns an unexpected error

## Extends

- [`LixCacheError`](/api/classes/lixcacheerror/)

## Constructors

### Constructor

> **new LixServerError**(`statusCode`, `response`): `LixServerError`

Defined in: lix-cache-sdk/src/errors.ts:92

#### Parameters

##### statusCode

`number`

##### response

`unknown`

#### Returns

`LixServerError`

#### Overrides

[`LixCacheError`](/api/classes/lixcacheerror/).[`constructor`](/api/classes/lixcacheerror/#constructor)

## Properties

### cause?

> `readonly` `optional` **cause**: `unknown`

Defined in: lix-cache-sdk/src/errors.ts:7

#### Inherited from

[`LixCacheError`](/api/classes/lixcacheerror/).[`cause`](/api/classes/lixcacheerror/#cause)

***

### message

> **message**: `string`

Defined in: node\_modules/.pnpm/typescript@5.9.3/node\_modules/typescript/lib/lib.es5.d.ts:1077

#### Inherited from

[`LixCacheError`](/api/classes/lixcacheerror/).[`message`](/api/classes/lixcacheerror/#message)

***

### name

> **name**: `string`

Defined in: node\_modules/.pnpm/typescript@5.9.3/node\_modules/typescript/lib/lib.es5.d.ts:1076

#### Inherited from

[`LixCacheError`](/api/classes/lixcacheerror/).[`name`](/api/classes/lixcacheerror/#name)

***

### response

> `readonly` **response**: `unknown`

Defined in: lix-cache-sdk/src/errors.ts:94

***

### stack?

> `optional` **stack**: `string`

Defined in: node\_modules/.pnpm/typescript@5.9.3/node\_modules/typescript/lib/lib.es5.d.ts:1078

#### Inherited from

[`LixCacheError`](/api/classes/lixcacheerror/).[`stack`](/api/classes/lixcacheerror/#stack)

***

### statusCode

> `readonly` **statusCode**: `number`

Defined in: lix-cache-sdk/src/errors.ts:93

***

### stackTraceLimit

> `static` **stackTraceLimit**: `number`

Defined in: node\_modules/.pnpm/@types+node@20.19.20/node\_modules/@types/node/globals.d.ts:68

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

[`LixCacheError`](/api/classes/lixcacheerror/).[`stackTraceLimit`](/api/classes/lixcacheerror/#stacktracelimit)

## Methods

### captureStackTrace()

> `static` **captureStackTrace**(`targetObject`, `constructorOpt?`): `void`

Defined in: node\_modules/.pnpm/@types+node@20.19.20/node\_modules/@types/node/globals.d.ts:52

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

##### targetObject

`object`

##### constructorOpt?

`Function`

#### Returns

`void`

#### Inherited from

[`LixCacheError`](/api/classes/lixcacheerror/).[`captureStackTrace`](/api/classes/lixcacheerror/#capturestacktrace)

***

### prepareStackTrace()

> `static` **prepareStackTrace**(`err`, `stackTraces`): `any`

Defined in: node\_modules/.pnpm/@types+node@20.19.20/node\_modules/@types/node/globals.d.ts:56

#### Parameters

##### err

`Error`

##### stackTraces

`CallSite`[]

#### Returns

`any`

#### See

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

[`LixCacheError`](/api/classes/lixcacheerror/).[`prepareStackTrace`](/api/classes/lixcacheerror/#preparestacktrace)
